/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const InquiryId = IDL.Nat;
export const Sector = IDL.Variant({
  'BPO' : IDL.Null,
  'BFSI' : IDL.Null,
  'NBFC' : IDL.Null,
  'Other' : IDL.Null,
});
export const Inquiry = IDL.Record({
  'id' : InquiryId,
  'name' : IDL.Text,
  'sector' : Sector,
  'company' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
  'staffCount' : IDL.Nat,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteInquiry' : IDL.Func([InquiryId], [], []),
  'getAllInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitInquiry' : IDL.Func(
      [IDL.Text, IDL.Text, Sector, IDL.Nat, IDL.Text, IDL.Int],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const InquiryId = IDL.Nat;
  const Sector = IDL.Variant({
    'BPO' : IDL.Null,
    'BFSI' : IDL.Null,
    'NBFC' : IDL.Null,
    'Other' : IDL.Null,
  });
  const Inquiry = IDL.Record({
    'id' : InquiryId,
    'name' : IDL.Text,
    'sector' : Sector,
    'company' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
    'staffCount' : IDL.Nat,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteInquiry' : IDL.Func([InquiryId], [], []),
    'getAllInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitInquiry' : IDL.Func(
        [IDL.Text, IDL.Text, Sector, IDL.Nat, IDL.Text, IDL.Int],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };